name: liminal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2

  # Firebase core + services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.0.0
  firebase_app_check: ^0.3.2+10

  # Helpers for nice UI/UX
  provider: ^6.1.2
  intl: ^0.19.0

  # Local notifications for task due/pre-reminder reminders
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Tool to generate the iOS App Icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/liminal-icon.png

# Configuration for the App Icon generator
flutter_launcher_icons:
  image_path: "assets/images/liminal-icon.png"
  ios: true
  android: false