// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfiwgh8dAVaBWHqiVoaq5Tq9vpeInmHzg',
    appId: '1:715032648373:web:3eb6e1fbc20326b710fcfc',
    messagingSenderId: '715032648373',
    projectId: 'student-task-management-system',
    authDomain: 'student-task-management-system.firebaseapp.com',
    storageBucket: 'student-task-management-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7UaV6UlUSoCD83Ugj6-saP8tBk5OaUg',
    appId: '1:715032648373:android:1d4a7972f86da77210fcfc',
    messagingSenderId: '715032648373',
    projectId: 'student-task-management-system',
    storageBucket: 'student-task-management-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGF4AB1xs3UFJ6DCk1T6FaylftWzjX0Y',
    appId: '1:715032648373:ios:07940b2d79e9af1910fcfc',
    messagingSenderId: '715032648373',
    projectId: 'student-task-management-system',
    storageBucket: 'student-task-management-system.firebasestorage.app',
    iosBundleId: 'com.example.liminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUGF4AB1xs3UFJ6DCk1T6FaylftWzjX0Y',
    appId: '1:715032648373:ios:07940b2d79e9af1910fcfc',
    messagingSenderId: '715032648373',
    projectId: 'student-task-management-system',
    storageBucket: 'student-task-management-system.firebasestorage.app',
    iosBundleId: 'com.example.liminal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfiwgh8dAVaBWHqiVoaq5Tq9vpeInmHzg',
    appId: '1:715032648373:web:8359111d9a5952b310fcfc',
    messagingSenderId: '715032648373',
    projectId: 'student-task-management-system',
    authDomain: 'student-task-management-system.firebaseapp.com',
    storageBucket: 'student-task-management-system.firebasestorage.app',
  );
}
